set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLUP [current_design]

set_property PACKAGE_PIN Y9 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN A16 [get_ports led]
set_property IOSTANDARD LVCMOS33 [get_ports led]

set_property PACKAGE_PIN A17 [get_ports reset_n_in]
set_property IOSTANDARD LVCMOS33 [get_ports reset_n_in]

set_property PACKAGE_PIN J18 [get_ports {rgmii1_rd[0]}]
set_property PACKAGE_PIN K18 [get_ports {rgmii1_rd[1]}]
set_property PACKAGE_PIN J15 [get_ports {rgmii1_rd[2]}]
set_property PACKAGE_PIN K15 [get_ports {rgmii1_rd[3]}]
set_property PACKAGE_PIN K20 [get_ports rgmii1_rx_ctl]
set_property PACKAGE_PIN K19 [get_ports rgmii1_rxc]
set_property PACKAGE_PIN N17 [get_ports {rgmii1_td[0]}]
set_property PACKAGE_PIN N18 [get_ports {rgmii1_td[1]}]
set_property PACKAGE_PIN N19 [get_ports {rgmii1_td[2]}]
set_property PACKAGE_PIN N20 [get_ports {rgmii1_td[3]}]
set_property PACKAGE_PIN R20 [get_ports rgmii1_tx_ctl]
set_property PACKAGE_PIN R21 [get_ports rgmii1_txc]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii1_rd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii1_rd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii1_rd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii1_rd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii1_rx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii1_rxc]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii1_td[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii1_td[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii1_td[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii1_td[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii1_tx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii1_txc]

set_property PACKAGE_PIN P18 [get_ports {rgmii2_rd[0]}]
set_property PACKAGE_PIN P22 [get_ports {rgmii2_rd[1]}]
set_property PACKAGE_PIN N22 [get_ports {rgmii2_rd[2]}]
set_property PACKAGE_PIN M21 [get_ports {rgmii2_rd[3]}]
set_property PACKAGE_PIN P17 [get_ports rgmii2_rx_ctl]
set_property PACKAGE_PIN M19 [get_ports rgmii2_rxc]
set_property PACKAGE_PIN L18 [get_ports {rgmii2_td[0]}]
set_property PACKAGE_PIN L22 [get_ports {rgmii2_td[1]}]
set_property PACKAGE_PIN L21 [get_ports {rgmii2_td[2]}]
set_property PACKAGE_PIN L16 [get_ports {rgmii2_td[3]}]
set_property PACKAGE_PIN M22 [get_ports rgmii2_tx_ctl]
set_property PACKAGE_PIN K16 [get_ports rgmii2_txc]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii2_rd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii2_rd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii2_rd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii2_rd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii2_rx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii2_rxc]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii2_td[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii2_td[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii2_td[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii2_td[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii2_tx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii2_txc]

set_property PACKAGE_PIN G16 [get_ports hdmi_out_clk]
set_property PACKAGE_PIN H22 [get_ports {hdmi_out_data[0]}]
set_property PACKAGE_PIN G22 [get_ports {hdmi_out_data[1]}]
set_property PACKAGE_PIN G17 [get_ports {hdmi_out_data[2]}]
set_property PACKAGE_PIN F17 [get_ports {hdmi_out_data[3]}]
set_property PACKAGE_PIN G15 [get_ports {hdmi_out_data[4]}]
set_property PACKAGE_PIN D15 [get_ports {hdmi_out_data[5]}]
set_property PACKAGE_PIN E15 [get_ports {hdmi_out_data[6]}]
set_property PACKAGE_PIN F18 [get_ports {hdmi_out_data[7]}]
set_property PACKAGE_PIN E18 [get_ports {hdmi_out_data[8]}]
set_property PACKAGE_PIN H17 [get_ports {hdmi_out_data[9]}]
set_property PACKAGE_PIN H18 [get_ports {hdmi_out_data[10]}]
set_property PACKAGE_PIN H19 [get_ports {hdmi_out_data[11]}]
set_property PACKAGE_PIN H20 [get_ports {hdmi_out_data[12]}]
set_property PACKAGE_PIN G19 [get_ports {hdmi_out_data[13]}]
set_property PACKAGE_PIN F19 [get_ports {hdmi_out_data[14]}]
set_property PACKAGE_PIN G20 [get_ports {hdmi_out_data[15]}]
set_property PACKAGE_PIN G21 [get_ports {hdmi_out_data[16]}]
set_property PACKAGE_PIN F21 [get_ports {hdmi_out_data[17]}]
set_property PACKAGE_PIN F22 [get_ports {hdmi_out_data[18]}]
set_property PACKAGE_PIN E21 [get_ports {hdmi_out_data[19]}]
set_property PACKAGE_PIN D21 [get_ports {hdmi_out_data[20]}]
set_property PACKAGE_PIN D22 [get_ports {hdmi_out_data[21]}]
set_property PACKAGE_PIN C22 [get_ports {hdmi_out_data[22]}]
set_property PACKAGE_PIN B21 [get_ports {hdmi_out_data[23]}]
set_property PACKAGE_PIN E20 [get_ports hdmi_out_de]
set_property PACKAGE_PIN E19 [get_ports hdmi_out_hs]
set_property PACKAGE_PIN C17 [get_ports {hdmi_rstn_tri_o[0]}]
set_property PACKAGE_PIN F16 [get_ports hdmi_out_vs]
set_property PACKAGE_PIN B22 [get_ports hdmi_i2c_scl_io]
set_property PACKAGE_PIN A22 [get_ports hdmi_i2c_sda_io]

set_property IOSTANDARD LVCMOS33 [get_ports hdmi_i2c_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_i2c_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_out_clk]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_out_de]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_out_hs]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_out_data[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_out_vs]
set_property IOSTANDARD LVCMOS33  [get_ports {hdmi_rstn_tri_o[0]}]

set_property SLEW FAST [get_ports {hdmi_out_data[*]}]
set_property DRIVE 8 [get_ports {hdmi_out_data[*]}]
set_property SLEW FAST [get_ports hdmi_out_clk]
set_property SLEW FAST [get_ports hdmi_out_de]
set_property SLEW FAST [get_ports hdmi_out_hs]
set_property SLEW FAST [get_ports hdmi_out_vs]