connect_debug_port u_ila_0/probe0 [get_nets [list {top_axi_inst/port_inst_0/tx_len_in[0]} {top_axi_inst/port_inst_0/tx_len_in[1]} {top_axi_inst/port_inst_0/tx_len_in[2]} {top_axi_inst/port_inst_0/tx_len_in[3]} {top_axi_inst/port_inst_0/tx_len_in[4]} {top_axi_inst/port_inst_0/tx_len_in[5]} {top_axi_inst/port_inst_0/tx_len_in[6]} {top_axi_inst/port_inst_0/tx_len_in[7]} {top_axi_inst/port_inst_0/tx_len_in[8]} {top_axi_inst/port_inst_0/tx_len_in[9]} {top_axi_inst/port_inst_0/tx_len_in[10]} {top_axi_inst/port_inst_0/tx_len_in[11]} {top_axi_inst/port_inst_0/tx_len_in[12]} {top_axi_inst/port_inst_0/tx_len_in[13]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list {top_axi_inst/port_inst_0/tx_data_in[0]} {top_axi_inst/port_inst_0/tx_data_in[1]} {top_axi_inst/port_inst_0/tx_data_in[2]} {top_axi_inst/port_inst_0/tx_data_in[3]} {top_axi_inst/port_inst_0/tx_data_in[4]} {top_axi_inst/port_inst_0/tx_data_in[5]} {top_axi_inst/port_inst_0/tx_data_in[6]} {top_axi_inst/port_inst_0/tx_data_in[7]}]]
connect_debug_port u_ila_0/probe5 [get_nets [list {top_axi_inst/fifo_matrix_tx_index[0]} {top_axi_inst/fifo_matrix_tx_index[1]}]]
connect_debug_port u_ila_0/probe7 [get_nets [list {top_axi_inst/fifo_matrix_tx_counter[0]} {top_axi_inst/fifo_matrix_tx_counter[1]} {top_axi_inst/fifo_matrix_tx_counter[2]} {top_axi_inst/fifo_matrix_tx_counter[3]} {top_axi_inst/fifo_matrix_tx_counter[4]} {top_axi_inst/fifo_matrix_tx_counter[5]} {top_axi_inst/fifo_matrix_tx_counter[6]} {top_axi_inst/fifo_matrix_tx_counter[7]} {top_axi_inst/fifo_matrix_tx_counter[8]} {top_axi_inst/fifo_matrix_tx_counter[9]} {top_axi_inst/fifo_matrix_tx_counter[10]} {top_axi_inst/fifo_matrix_tx_counter[11]} {top_axi_inst/fifo_matrix_tx_counter[12]} {top_axi_inst/fifo_matrix_tx_counter[13]}]]
connect_debug_port u_ila_0/probe9 [get_nets [list {top_axi_inst/port_inst_1/tx_len_in[0]} {top_axi_inst/port_inst_1/tx_len_in[1]} {top_axi_inst/port_inst_1/tx_len_in[2]} {top_axi_inst/port_inst_1/tx_len_in[3]} {top_axi_inst/port_inst_1/tx_len_in[4]} {top_axi_inst/port_inst_1/tx_len_in[5]} {top_axi_inst/port_inst_1/tx_len_in[6]} {top_axi_inst/port_inst_1/tx_len_in[7]} {top_axi_inst/port_inst_1/tx_len_in[8]} {top_axi_inst/port_inst_1/tx_len_in[9]} {top_axi_inst/port_inst_1/tx_len_in[10]} {top_axi_inst/port_inst_1/tx_len_in[11]} {top_axi_inst/port_inst_1/tx_len_in[12]} {top_axi_inst/port_inst_1/tx_len_in[13]}]]
connect_debug_port u_ila_0/probe10 [get_nets [list {top_axi_inst/port_inst_1/fifo_matrix_tx_length[0]} {top_axi_inst/port_inst_1/fifo_matrix_tx_length[1]} {top_axi_inst/port_inst_1/fifo_matrix_tx_length[2]} {top_axi_inst/port_inst_1/fifo_matrix_tx_length[3]} {top_axi_inst/port_inst_1/fifo_matrix_tx_length[4]} {top_axi_inst/port_inst_1/fifo_matrix_tx_length[5]} {top_axi_inst/port_inst_1/fifo_matrix_tx_length[6]} {top_axi_inst/port_inst_1/fifo_matrix_tx_length[7]} {top_axi_inst/port_inst_1/fifo_matrix_tx_length[8]} {top_axi_inst/port_inst_1/fifo_matrix_tx_length[9]} {top_axi_inst/port_inst_1/fifo_matrix_tx_length[10]} {top_axi_inst/port_inst_1/fifo_matrix_tx_length[11]} {top_axi_inst/port_inst_1/fifo_matrix_tx_length[12]} {top_axi_inst/port_inst_1/fifo_matrix_tx_length[13]}]]
connect_debug_port u_ila_0/probe11 [get_nets [list {top_axi_inst/port_inst_1/tx_data_in[0]} {top_axi_inst/port_inst_1/tx_data_in[1]} {top_axi_inst/port_inst_1/tx_data_in[2]} {top_axi_inst/port_inst_1/tx_data_in[3]} {top_axi_inst/port_inst_1/tx_data_in[4]} {top_axi_inst/port_inst_1/tx_data_in[5]} {top_axi_inst/port_inst_1/tx_data_in[6]} {top_axi_inst/port_inst_1/tx_data_in[7]}]]
connect_debug_port u_ila_0/probe12 [get_nets [list {top_axi_inst/port_inst_1/fifo_matrix_tx_index[0]} {top_axi_inst/port_inst_1/fifo_matrix_tx_index[1]} {top_axi_inst/port_inst_1/fifo_matrix_tx_index[2]}]]
connect_debug_port u_ila_0/probe13 [get_nets [list {top_axi_inst/port_inst_0/fifo_matrix_tx_length[0]} {top_axi_inst/port_inst_0/fifo_matrix_tx_length[1]} {top_axi_inst/port_inst_0/fifo_matrix_tx_length[2]} {top_axi_inst/port_inst_0/fifo_matrix_tx_length[3]} {top_axi_inst/port_inst_0/fifo_matrix_tx_length[4]} {top_axi_inst/port_inst_0/fifo_matrix_tx_length[5]} {top_axi_inst/port_inst_0/fifo_matrix_tx_length[6]} {top_axi_inst/port_inst_0/fifo_matrix_tx_length[7]} {top_axi_inst/port_inst_0/fifo_matrix_tx_length[8]} {top_axi_inst/port_inst_0/fifo_matrix_tx_length[9]} {top_axi_inst/port_inst_0/fifo_matrix_tx_length[10]} {top_axi_inst/port_inst_0/fifo_matrix_tx_length[11]} {top_axi_inst/port_inst_0/fifo_matrix_tx_length[12]} {top_axi_inst/port_inst_0/fifo_matrix_tx_length[13]}]]
connect_debug_port u_ila_0/probe14 [get_nets [list {top_axi_inst/port_inst_0/fifo_matrix_tx_index[0]} {top_axi_inst/port_inst_0/fifo_matrix_tx_index[1]} {top_axi_inst/port_inst_0/fifo_matrix_tx_index[2]}]]
connect_debug_port u_ila_0/probe22 [get_nets [list top_axi_inst/os_txd_tready]]
connect_debug_port u_ila_0/probe26 [get_nets [list top_axi_inst/port_inst_0/tx_data_full]]
connect_debug_port u_ila_0/probe27 [get_nets [list top_axi_inst/port_inst_1/tx_data_full]]
connect_debug_port u_ila_0/probe28 [get_nets [list top_axi_inst/port_inst_0/tx_data_wen]]
connect_debug_port u_ila_0/probe29 [get_nets [list top_axi_inst/port_inst_1/tx_data_wen]]
connect_debug_port u_ila_0/probe30 [get_nets [list top_axi_inst/port_inst_0/tx_len_busy]]
connect_debug_port u_ila_0/probe31 [get_nets [list top_axi_inst/port_inst_1/tx_len_busy]]
connect_debug_port u_ila_0/probe32 [get_nets [list top_axi_inst/port_inst_0/tx_len_full]]
connect_debug_port u_ila_0/probe33 [get_nets [list top_axi_inst/port_inst_1/tx_len_full]]
connect_debug_port u_ila_1/probe0 [get_nets [list {top_axi_inst/port_inst_0/tx_data_out[0]} {top_axi_inst/port_inst_0/tx_data_out[1]} {top_axi_inst/port_inst_0/tx_data_out[2]} {top_axi_inst/port_inst_0/tx_data_out[3]} {top_axi_inst/port_inst_0/tx_data_out[4]} {top_axi_inst/port_inst_0/tx_data_out[5]} {top_axi_inst/port_inst_0/tx_data_out[6]} {top_axi_inst/port_inst_0/tx_data_out[7]}]]
connect_debug_port u_ila_1/probe1 [get_nets [list {top_axi_inst/port_inst_0/tx_len_out[0]} {top_axi_inst/port_inst_0/tx_len_out[1]} {top_axi_inst/port_inst_0/tx_len_out[2]} {top_axi_inst/port_inst_0/tx_len_out[3]} {top_axi_inst/port_inst_0/tx_len_out[4]} {top_axi_inst/port_inst_0/tx_len_out[5]} {top_axi_inst/port_inst_0/tx_len_out[6]} {top_axi_inst/port_inst_0/tx_len_out[7]} {top_axi_inst/port_inst_0/tx_len_out[8]} {top_axi_inst/port_inst_0/tx_len_out[9]} {top_axi_inst/port_inst_0/tx_len_out[10]} {top_axi_inst/port_inst_0/tx_len_out[11]} {top_axi_inst/port_inst_0/tx_len_out[12]} {top_axi_inst/port_inst_0/tx_len_out[13]}]]
connect_debug_port u_ila_1/probe2 [get_nets [list {top_axi_inst/port_inst_1/tx_data_out[0]} {top_axi_inst/port_inst_1/tx_data_out[1]} {top_axi_inst/port_inst_1/tx_data_out[2]} {top_axi_inst/port_inst_1/tx_data_out[3]} {top_axi_inst/port_inst_1/tx_data_out[4]} {top_axi_inst/port_inst_1/tx_data_out[5]} {top_axi_inst/port_inst_1/tx_data_out[6]} {top_axi_inst/port_inst_1/tx_data_out[7]}]]
connect_debug_port u_ila_1/probe3 [get_nets [list {top_axi_inst/port_inst_1/tx_len_out[0]} {top_axi_inst/port_inst_1/tx_len_out[1]} {top_axi_inst/port_inst_1/tx_len_out[2]} {top_axi_inst/port_inst_1/tx_len_out[3]} {top_axi_inst/port_inst_1/tx_len_out[4]} {top_axi_inst/port_inst_1/tx_len_out[5]} {top_axi_inst/port_inst_1/tx_len_out[6]} {top_axi_inst/port_inst_1/tx_len_out[7]} {top_axi_inst/port_inst_1/tx_len_out[8]} {top_axi_inst/port_inst_1/tx_len_out[9]} {top_axi_inst/port_inst_1/tx_len_out[10]} {top_axi_inst/port_inst_1/tx_len_out[11]} {top_axi_inst/port_inst_1/tx_len_out[12]} {top_axi_inst/port_inst_1/tx_len_out[13]}]]
connect_debug_port u_ila_1/probe6 [get_nets [list top_axi_inst/port_inst_0/tx_len_empty]]
connect_debug_port u_ila_1/probe7 [get_nets [list top_axi_inst/port_inst_1/tx_len_empty]]
connect_debug_port u_ila_1/probe8 [get_nets [list top_axi_inst/port_inst_1/tx_len_ren]]
connect_debug_port u_ila_1/probe9 [get_nets [list top_axi_inst/port_inst_0/tx_len_ren]]


set_property MARK_DEBUG true [get_nets {os_addr[0]}]
set_property MARK_DEBUG true [get_nets {os_addr[1]}]
set_property MARK_DEBUG true [get_nets {os_addr[2]}]
set_property MARK_DEBUG true [get_nets {os_din[50]}]
set_property MARK_DEBUG true [get_nets {os_din[30]}]
set_property MARK_DEBUG true [get_nets {os_din[14]}]
set_property MARK_DEBUG true [get_nets {os_din[2]}]
set_property MARK_DEBUG true [get_nets {os_din[6]}]
set_property MARK_DEBUG true [get_nets {os_din[22]}]
set_property MARK_DEBUG true [get_nets {os_din[38]}]
set_property MARK_DEBUG true [get_nets {os_din[46]}]
set_property MARK_DEBUG true [get_nets {os_din[54]}]
set_property MARK_DEBUG true [get_nets {os_din[62]}]
set_property MARK_DEBUG true [get_nets {os_din[58]}]
set_property MARK_DEBUG true [get_nets {os_din[70]}]
set_property MARK_DEBUG true [get_nets {os_din[66]}]
set_property MARK_DEBUG true [get_nets {os_din[78]}]
set_property MARK_DEBUG true [get_nets {os_din[74]}]
set_property MARK_DEBUG true [get_nets {os_din[86]}]
set_property MARK_DEBUG true [get_nets {os_din[82]}]
set_property MARK_DEBUG true [get_nets {os_din[94]}]
set_property MARK_DEBUG true [get_nets {os_din[90]}]
set_property MARK_DEBUG true [get_nets {os_din[42]}]
set_property MARK_DEBUG true [get_nets {os_din[34]}]
set_property MARK_DEBUG true [get_nets {os_din[26]}]
set_property MARK_DEBUG true [get_nets {os_din[18]}]
set_property MARK_DEBUG true [get_nets {os_din[10]}]
set_property MARK_DEBUG true [get_nets {os_din[25]}]
set_property MARK_DEBUG true [get_nets {os_din[1]}]
set_property MARK_DEBUG true [get_nets {os_din[13]}]
set_property MARK_DEBUG true [get_nets {os_din[5]}]
set_property MARK_DEBUG true [get_nets {os_din[8]}]
set_property MARK_DEBUG true [get_nets {os_din[21]}]
set_property MARK_DEBUG true [get_nets {os_din[17]}]
set_property MARK_DEBUG true [get_nets {os_din[29]}]
set_property MARK_DEBUG true [get_nets {os_din[37]}]
set_property MARK_DEBUG true [get_nets {os_din[33]}]
set_property MARK_DEBUG true [get_nets {os_din[45]}]
set_property MARK_DEBUG true [get_nets {os_din[41]}]
set_property MARK_DEBUG true [get_nets {os_din[49]}]
set_property MARK_DEBUG true [get_nets {os_din[53]}]
set_property MARK_DEBUG true [get_nets {os_din[61]}]
set_property MARK_DEBUG true [get_nets {os_din[57]}]
set_property MARK_DEBUG true [get_nets {os_din[69]}]
set_property MARK_DEBUG true [get_nets {os_din[65]}]
set_property MARK_DEBUG true [get_nets {os_din[77]}]
set_property MARK_DEBUG true [get_nets {os_din[73]}]
set_property MARK_DEBUG true [get_nets {os_din[85]}]
set_property MARK_DEBUG true [get_nets {os_din[81]}]
set_property MARK_DEBUG true [get_nets {os_din[93]}]
set_property MARK_DEBUG true [get_nets {os_din[89]}]
set_property MARK_DEBUG true [get_nets {os_din[97]}]
set_property MARK_DEBUG true [get_nets {os_din[44]}]
set_property MARK_DEBUG true [get_nets {os_din[0]}]
set_property MARK_DEBUG true [get_nets {os_din[16]}]
set_property MARK_DEBUG true [get_nets {os_din[4]}]
set_property MARK_DEBUG true [get_nets {os_din[7]}]
set_property MARK_DEBUG true [get_nets {os_din[24]}]
set_property MARK_DEBUG true [get_nets {os_din[32]}]
set_property MARK_DEBUG true [get_nets {os_din[40]}]
set_property MARK_DEBUG true [get_nets {os_din[48]}]
set_property MARK_DEBUG true [get_nets {os_din[56]}]
set_property MARK_DEBUG true [get_nets {os_din[52]}]
set_property MARK_DEBUG true [get_nets {os_din[64]}]
set_property MARK_DEBUG true [get_nets {os_din[60]}]
set_property MARK_DEBUG true [get_nets {os_din[72]}]
set_property MARK_DEBUG true [get_nets {os_din[68]}]
set_property MARK_DEBUG true [get_nets {os_din[80]}]
set_property MARK_DEBUG true [get_nets {os_din[76]}]
set_property MARK_DEBUG true [get_nets {os_din[88]}]
set_property MARK_DEBUG true [get_nets {os_din[84]}]
set_property MARK_DEBUG true [get_nets {os_din[96]}]
set_property MARK_DEBUG true [get_nets {os_din[92]}]
set_property MARK_DEBUG true [get_nets {os_din[36]}]
set_property MARK_DEBUG true [get_nets {os_din[28]}]
set_property MARK_DEBUG true [get_nets {os_din[20]}]
set_property MARK_DEBUG true [get_nets {os_din[12]}]
set_property MARK_DEBUG true [get_nets {os_din[39]}]
set_property MARK_DEBUG true [get_nets {os_din[23]}]
set_property MARK_DEBUG true [get_nets {os_din[3]}]
set_property MARK_DEBUG true [get_nets {os_din[15]}]
set_property MARK_DEBUG true [get_nets {os_din[11]}]
set_property MARK_DEBUG true [get_nets {os_din[19]}]
set_property MARK_DEBUG true [get_nets {os_din[31]}]
set_property MARK_DEBUG true [get_nets {os_din[27]}]
set_property MARK_DEBUG true [get_nets {os_din[35]}]
set_property MARK_DEBUG true [get_nets {os_din[47]}]
set_property MARK_DEBUG true [get_nets {os_din[43]}]
set_property MARK_DEBUG true [get_nets {os_din[55]}]
set_property MARK_DEBUG true [get_nets {os_din[51]}]
set_property MARK_DEBUG true [get_nets {os_din[63]}]
set_property MARK_DEBUG true [get_nets {os_din[59]}]
set_property MARK_DEBUG true [get_nets {os_din[71]}]
set_property MARK_DEBUG true [get_nets {os_din[67]}]
set_property MARK_DEBUG true [get_nets {os_din[79]}]
set_property MARK_DEBUG true [get_nets {os_din[75]}]
set_property MARK_DEBUG true [get_nets {os_din[87]}]
set_property MARK_DEBUG true [get_nets {os_din[83]}]
set_property MARK_DEBUG true [get_nets {os_din[95]}]
set_property MARK_DEBUG true [get_nets {os_din[91]}]
set_property MARK_DEBUG true [get_nets {os_din[9]}]
set_property MARK_DEBUG true [get_nets os_en]
set_property MARK_DEBUG true [get_nets os_rst]
set_property MARK_DEBUG true [get_nets {os_wea[0]}]
set_property MARK_DEBUG true [get_nets {os_dout[28]}]
set_property MARK_DEBUG true [get_nets {os_dout[7]}]
set_property MARK_DEBUG true [get_nets {os_dout[0]}]
set_property MARK_DEBUG true [get_nets {os_dout[12]}]
set_property MARK_DEBUG true [get_nets {os_dout[4]}]
set_property MARK_DEBUG true [get_nets {os_dout[20]}]
set_property MARK_DEBUG true [get_nets {os_dout[36]}]
set_property MARK_DEBUG true [get_nets {os_dout[44]}]
set_property MARK_DEBUG true [get_nets {os_dout[48]}]
set_property MARK_DEBUG true [get_nets {os_dout[52]}]
set_property MARK_DEBUG true [get_nets {os_dout[60]}]
set_property MARK_DEBUG true [get_nets {os_dout[56]}]
set_property MARK_DEBUG true [get_nets {os_dout[68]}]
set_property MARK_DEBUG true [get_nets {os_dout[64]}]
set_property MARK_DEBUG true [get_nets {os_dout[76]}]
set_property MARK_DEBUG true [get_nets {os_dout[72]}]
set_property MARK_DEBUG true [get_nets {os_dout[40]}]
set_property MARK_DEBUG true [get_nets {os_dout[32]}]
set_property MARK_DEBUG true [get_nets {os_dout[24]}]
set_property MARK_DEBUG true [get_nets {os_dout[16]}]
set_property MARK_DEBUG true [get_nets {os_dout[80]}]
set_property MARK_DEBUG true [get_nets {os_dout[84]}]
set_property MARK_DEBUG true [get_nets {os_dout[88]}]
set_property MARK_DEBUG true [get_nets {os_dout[92]}]
set_property MARK_DEBUG true [get_nets {os_dout[96]}]
set_property MARK_DEBUG true [get_nets {os_dout[31]}]
set_property MARK_DEBUG true [get_nets {os_dout[11]}]
set_property MARK_DEBUG true [get_nets {os_dout[3]}]
set_property MARK_DEBUG true [get_nets {os_dout[19]}]
set_property MARK_DEBUG true [get_nets {os_dout[15]}]
set_property MARK_DEBUG true [get_nets {os_dout[27]}]
set_property MARK_DEBUG true [get_nets {os_dout[23]}]
set_property MARK_DEBUG true [get_nets {os_dout[35]}]
set_property MARK_DEBUG true [get_nets {os_dout[43]}]
set_property MARK_DEBUG true [get_nets {os_dout[39]}]
set_property MARK_DEBUG true [get_nets {os_dout[47]}]
set_property MARK_DEBUG true [get_nets {os_dout[51]}]
set_property MARK_DEBUG true [get_nets {os_dout[59]}]
set_property MARK_DEBUG true [get_nets {os_dout[55]}]
set_property MARK_DEBUG true [get_nets {os_dout[67]}]
set_property MARK_DEBUG true [get_nets {os_dout[63]}]
set_property MARK_DEBUG true [get_nets {os_dout[75]}]
set_property MARK_DEBUG true [get_nets {os_dout[71]}]
set_property MARK_DEBUG true [get_nets {os_dout[9]}]
set_property MARK_DEBUG true [get_nets {os_dout[79]}]
set_property MARK_DEBUG true [get_nets {os_dout[83]}]
set_property MARK_DEBUG true [get_nets {os_dout[87]}]
set_property MARK_DEBUG true [get_nets {os_dout[91]}]
set_property MARK_DEBUG true [get_nets {os_dout[95]}]
set_property MARK_DEBUG true [get_nets {os_dout[22]}]
set_property MARK_DEBUG true [get_nets {os_dout[14]}]
set_property MARK_DEBUG true [get_nets {os_dout[2]}]
set_property MARK_DEBUG true [get_nets {os_dout[6]}]
set_property MARK_DEBUG true [get_nets {os_dout[30]}]
set_property MARK_DEBUG true [get_nets {os_dout[38]}]
set_property MARK_DEBUG true [get_nets {os_dout[46]}]
set_property MARK_DEBUG true [get_nets {os_dout[54]}]
set_property MARK_DEBUG true [get_nets {os_dout[50]}]
set_property MARK_DEBUG true [get_nets {os_dout[62]}]
set_property MARK_DEBUG true [get_nets {os_dout[58]}]
set_property MARK_DEBUG true [get_nets {os_dout[70]}]
set_property MARK_DEBUG true [get_nets {os_dout[66]}]
set_property MARK_DEBUG true [get_nets {os_dout[78]}]
set_property MARK_DEBUG true [get_nets {os_dout[74]}]
set_property MARK_DEBUG true [get_nets {os_dout[42]}]
set_property MARK_DEBUG true [get_nets {os_dout[34]}]
set_property MARK_DEBUG true [get_nets {os_dout[26]}]
set_property MARK_DEBUG true [get_nets {os_dout[18]}]
set_property MARK_DEBUG true [get_nets {os_dout[10]}]
set_property MARK_DEBUG true [get_nets {os_dout[82]}]
set_property MARK_DEBUG true [get_nets {os_dout[86]}]
set_property MARK_DEBUG true [get_nets {os_dout[90]}]
set_property MARK_DEBUG true [get_nets {os_dout[94]}]
set_property MARK_DEBUG true [get_nets {os_dout[37]}]
set_property MARK_DEBUG true [get_nets {os_dout[17]}]
set_property MARK_DEBUG true [get_nets {os_dout[1]}]
set_property MARK_DEBUG true [get_nets {os_dout[13]}]
set_property MARK_DEBUG true [get_nets {os_dout[5]}]
set_property MARK_DEBUG true [get_nets {os_dout[8]}]
set_property MARK_DEBUG true [get_nets {os_dout[21]}]
set_property MARK_DEBUG true [get_nets {os_dout[29]}]
set_property MARK_DEBUG true [get_nets {os_dout[25]}]
set_property MARK_DEBUG true [get_nets {os_dout[33]}]
set_property MARK_DEBUG true [get_nets {os_dout[45]}]
set_property MARK_DEBUG true [get_nets {os_dout[41]}]
set_property MARK_DEBUG true [get_nets {os_dout[53]}]
set_property MARK_DEBUG true [get_nets {os_dout[49]}]
set_property MARK_DEBUG true [get_nets {os_dout[61]}]
set_property MARK_DEBUG true [get_nets {os_dout[57]}]
set_property MARK_DEBUG true [get_nets {os_dout[69]}]
set_property MARK_DEBUG true [get_nets {os_dout[65]}]
set_property MARK_DEBUG true [get_nets {os_dout[77]}]
set_property MARK_DEBUG true [get_nets {os_dout[73]}]
set_property MARK_DEBUG true [get_nets {os_dout[81]}]
set_property MARK_DEBUG true [get_nets {os_dout[85]}]
set_property MARK_DEBUG true [get_nets {os_dout[89]}]
set_property MARK_DEBUG true [get_nets {os_dout[93]}]
set_property MARK_DEBUG true [get_nets {os_dout[97]}]
connect_debug_port u_ila_0/probe0 [get_nets [list {os_addr[0]} {os_addr[1]} {os_addr[2]}]]

set_property MARK_DEBUG true [get_nets {os_addr[4]}]
set_property MARK_DEBUG true [get_nets {os_addr[5]}]
set_property MARK_DEBUG true [get_nets {os_addr[6]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_inst/design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 3 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {os_addr[4]} {os_addr[5]} {os_addr[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 128 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {os_din[0]} {os_din[1]} {os_din[2]} {os_din[3]} {os_din[4]} {os_din[5]} {os_din[6]} {os_din[7]} {os_din[8]} {os_din[9]} {os_din[10]} {os_din[11]} {os_din[12]} {os_din[13]} {os_din[14]} {os_din[15]} {os_din[16]} {os_din[17]} {os_din[18]} {os_din[19]} {os_din[20]} {os_din[21]} {os_din[22]} {os_din[23]} {os_din[24]} {os_din[25]} {os_din[26]} {os_din[27]} {os_din[28]} {os_din[29]} {os_din[30]} {os_din[31]} {os_din[32]} {os_din[33]} {os_din[34]} {os_din[35]} {os_din[36]} {os_din[37]} {os_din[38]} {os_din[39]} {os_din[40]} {os_din[41]} {os_din[42]} {os_din[43]} {os_din[44]} {os_din[45]} {os_din[46]} {os_din[47]} {os_din[48]} {os_din[49]} {os_din[50]} {os_din[51]} {os_din[52]} {os_din[53]} {os_din[54]} {os_din[55]} {os_din[56]} {os_din[57]} {os_din[58]} {os_din[59]} {os_din[60]} {os_din[61]} {os_din[62]} {os_din[63]} {os_din[64]} {os_din[65]} {os_din[66]} {os_din[67]} {os_din[68]} {os_din[69]} {os_din[70]} {os_din[71]} {os_din[72]} {os_din[73]} {os_din[74]} {os_din[75]} {os_din[76]} {os_din[77]} {os_din[78]} {os_din[79]} {os_din[80]} {os_din[81]} {os_din[82]} {os_din[83]} {os_din[84]} {os_din[85]} {os_din[86]} {os_din[87]} {os_din[88]} {os_din[89]} {os_din[90]} {os_din[91]} {os_din[92]} {os_din[93]} {os_din[94]} {os_din[95]} {os_din[96]} {os_din[97]} {os_din[98]} {os_din[99]} {os_din[100]} {os_din[101]} {os_din[102]} {os_din[103]} {os_din[104]} {os_din[105]} {os_din[106]} {os_din[107]} {os_din[108]} {os_din[109]} {os_din[110]} {os_din[111]} {os_din[112]} {os_din[113]} {os_din[114]} {os_din[115]} {os_din[116]} {os_din[117]} {os_din[118]} {os_din[119]} {os_din[120]} {os_din[121]} {os_din[122]} {os_din[123]} {os_din[124]} {os_din[125]} {os_din[126]} {os_din[127]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 98 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {os_dout[0]} {os_dout[1]} {os_dout[2]} {os_dout[3]} {os_dout[4]} {os_dout[5]} {os_dout[6]} {os_dout[7]} {os_dout[8]} {os_dout[9]} {os_dout[10]} {os_dout[11]} {os_dout[12]} {os_dout[13]} {os_dout[14]} {os_dout[15]} {os_dout[16]} {os_dout[17]} {os_dout[18]} {os_dout[19]} {os_dout[20]} {os_dout[21]} {os_dout[22]} {os_dout[23]} {os_dout[24]} {os_dout[25]} {os_dout[26]} {os_dout[27]} {os_dout[28]} {os_dout[29]} {os_dout[30]} {os_dout[31]} {os_dout[32]} {os_dout[33]} {os_dout[34]} {os_dout[35]} {os_dout[36]} {os_dout[37]} {os_dout[38]} {os_dout[39]} {os_dout[40]} {os_dout[41]} {os_dout[42]} {os_dout[43]} {os_dout[44]} {os_dout[45]} {os_dout[46]} {os_dout[47]} {os_dout[48]} {os_dout[49]} {os_dout[50]} {os_dout[51]} {os_dout[52]} {os_dout[53]} {os_dout[54]} {os_dout[55]} {os_dout[56]} {os_dout[57]} {os_dout[58]} {os_dout[59]} {os_dout[60]} {os_dout[61]} {os_dout[62]} {os_dout[63]} {os_dout[64]} {os_dout[65]} {os_dout[66]} {os_dout[67]} {os_dout[68]} {os_dout[69]} {os_dout[70]} {os_dout[71]} {os_dout[72]} {os_dout[73]} {os_dout[74]} {os_dout[75]} {os_dout[76]} {os_dout[77]} {os_dout[78]} {os_dout[79]} {os_dout[80]} {os_dout[81]} {os_dout[82]} {os_dout[83]} {os_dout[84]} {os_dout[85]} {os_dout[86]} {os_dout[87]} {os_dout[88]} {os_dout[89]} {os_dout[90]} {os_dout[91]} {os_dout[92]} {os_dout[93]} {os_dout[94]} {os_dout[95]} {os_dout[96]} {os_dout[97]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 16 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {os_wea[0]} {os_wea[1]} {os_wea[2]} {os_wea[3]} {os_wea[4]} {os_wea[5]} {os_wea[6]} {os_wea[7]} {os_wea[8]} {os_wea[9]} {os_wea[10]} {os_wea[11]} {os_wea[12]} {os_wea[13]} {os_wea[14]} {os_wea[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list os_en]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list os_rst]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets axis_clk]
